USE[master]
GO

/****** Object:  Database [taskboard]    Script Date: 2021-01-19 16:19:19 ******/
CREATE DATABASE [taskboard]
GO

IF(1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC[taskboard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [taskboard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [taskboard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [taskboard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [taskboard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [taskboard] SET ARITHABORT OFF 
GO

ALTER DATABASE [taskboard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [taskboard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [taskboard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [taskboard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [taskboard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [taskboard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [taskboard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [taskboard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [taskboard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [taskboard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [taskboard] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [taskboard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [taskboard] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [taskboard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [taskboard] SET MULTI_USER 
GO

ALTER DATABASE [taskboard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [taskboard] SET QUERY_STORE = ON
GO

ALTER DATABASE [taskboard] SET QUERY_STORE(OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

ALTER DATABASE [taskboard] SET READ_WRITE 
GO


-- Create tables

USE [taskboard]
GO
/****** Object:  Table [dbo].[TaskLists]    Script Date: 2021-01-19 16:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskLists](

[Id][int] IDENTITY(1, 1) NOT NULL,

[Name] [varchar](max)NOT NULL,
 CONSTRAINT[PK_TaskLists] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 2021-01-19 16:20:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](

[Id][int] IDENTITY(1, 1) NOT NULL,

[TaskListId] [int] NOT NULL,

[Name] [varchar](max)NOT NULL,
	[Description] [varchar](max)NOT NULL,
 CONSTRAINT[PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
